name: Bulid & Deploy DotNet app


on:
  workflow_dispatch:


jobs:
   build-depoly:
      name: Build and deply DotNet for beginner 
      runs-on: windows-latest 
      steps: 
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .Net 8
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.x'

        - name: Install dependencies
          run: dotnet restore

        - name: Build the project
          run: dotnet build --configuration Release --no-restore



